### ISSUE TITLE
Incorrect condition

### ISSUE THREAD

**Issue by nethask** [AndrewKhodyakov/qsh_parser#1]
https://github.com/AndrewKhodyakov/qsh_parser/blob/8f7b99b5ff68dd85a2a683e2d232586d95744fd5/qsh_parser.py#L224

As far as I understand there must be `if _tmp > 268435454:` OR `if _tmp == 268435455:`.

**Comment by AndrewKhodyakov** [comment]
it seems, that my solution and your suggestion, are doing a same things, isnt it? 
But your a little bit faster :

In [1]: def test1(a):
   ...:     if a >= 5:
   ...:         return a

In [2]: def test2(a):
   ...:     if a > 5 or a == 5: 
   ...:         return a

In [3]: %timeit(test1(6))
104 ns ± 1.04 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)

In [4]: %timeit(test2(6))
103 ns ± 1.09 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)

**Comment by nethask** [comment]
Nope, it isn't. It's not a question of how fast the code is executed. You need to be sure that your `_tmp` is equal to 268435455 to read next signed leb128 in your turn you compare it with 268435454 (which is less by 1). So there can be a case when your `_tmp` is equal to 268435454 but you try to read next signed leb128 which is not there.

**Comment by AndrewKhodyakov** [comment]
Thank you for your suggestions, bug was fixed.
