### ISSUE TITLE
Парсить OrdLog файлы

### ISSUE THREAD

**Issue by BatyaGG** [AndrewKhodyakov/qsh_parser#3]
Здравствуйте Андрей,

Не могли бы помочь с парсингом OrdLog.qsh файлов? я пытаюсь распарсить файл RTS-3.19.2019-02-15.OrdLog.qsh по ссылке ftp://zerich.qscalp.ru/2019-02-15/ у меня выходит ошибка
![image](https://user-images.githubusercontent.com/25902664/52946874-50355580-339f-11e9-9443-d4a0cd462e54.png)

Заранее спасибо!

**Comment by AndrewKhodyakov** [comment]
Ок, гляну в ближайшее время.

**Comment by AndrewKhodyakov** [comment]
Надо узнать какая в этих данных версия формата - я делал для 4 ой - согласно этому описанию https://www.qscalp.ru/store/qsh.pdf. В Вашем случае парсер не может  прочитать  заголовок файла  - потому что он не соотвествует  спецификации.

**Comment by AndrewKhodyakov** [comment]
KhodyakovAnd:~/work_repo/qsh_parser$ file ./RTS-3.19.2019-02-15.OrdLog.qsh 
./RTS-3.19.2019-02-15.OrdLog.qsh: gzip compressed data, was "RTS-3.19.2019-02-15.OrdLog.qsh", last modified: Fri Feb 15 20:56:31 2019, max compression, from FAT filesystem (MS-DOS, OS/2, NT) - понятно почему он не читался

 - это gzip сжатый в FAT - согласно документации https://www.qscalp.ru/store/qsh.pdf на странице 3 : " ... Файлы в формате QSH после окончания записи могут быть дополнительно сжаты с помощью gzip компрессии. При этом расширение файла может быть оставлено первоначальным (.qsh) или же изменено
путем добавления к нему соответствующего окончания (.qsh.gz). Сжатые файлы воспроизводятся наравне
с несжатыми, а наличие компрессии определяется путем анализа заголовка файла."

**Comment by BatyaGG** [comment]
Все понял, спасибо. У меня получилось его разархивировать, теперь выходит другая ошибка:

![image](https://user-images.githubusercontent.com/25902664/53067068-c3a0a980-34fc-11e9-8c51-79341e636c65.png)

**Comment by AndrewKhodyakov** [comment]
В README.txt написано что на данный момент parser - поддерживает два типа потоков данных, которые записываются в формате qsh - Quotes и Deals. В том файле, который вы пытаетесь распарсить - записан поток данных OrderLog - такой тип на данный момент времени  - не поддерживается - это будет выполнено  в рамках https://github.com/AndrewKhodyakov/qsh_parser/issues/4 , по мере моих возможностей разумеется

**Comment by BatyaGG** [comment]
Окей понял спасибо!
